#!/usr/bin/env python3
"""
The weekly refresh. One run keeps a chapter current.

    python3 shared/weekly.py --all
    python3 shared/weekly.py houston dallas
    python3 shared/weekly.py --all --deploy

Steps, per chapter, in order:

    1. meetings     pull new agendas/minutes/video from the city's own portal
    2. links        re-fetch every external link the chapter publishes
    3. build        re-render the site
    4. search       rebuild the client-side search index
    5. automation   write data/automation.json - what ran, when, and what failed

Every step is wrapped. A city portal that is down on a Sunday morning must not
stop the other ten chapters from refreshing, and must not stop THIS chapter from
rebuilding: the pages that do not depend on the failed step are still better off
current. The failure is recorded and published instead of being swallowed.

data/automation.json is the contract with the public automation page. It is
written on every run, including runs where everything failed, because a status
file that only appears when things go well is not a status file.
"""

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = ROOT / "chapters"
PY = sys.executable or "python3"

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except AttributeError:
    pass


def now():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load(key):
    return json.loads((CHAPTERS / f"{key}.json").read_text(encoding="utf-8"))


def city_keys():
    """Chapters this run refreshes: every template-built one this tree owns.

    A `managed` value means another pipeline owns the chapter's build and deploy,
    and this run must not touch it:

      managed=legacy   Miami OK, generated by its own scripts.
      managed=refresh  San Angelo and Southaven, built twice daily by refresh.sh
                       from source material this tree does not hold.

    Both were briefly included here to fix a stale chapter bar. That was the
    wrong lever: it made two pipelines overwrite each other every twelve hours,
    each undoing the other's work. The bar is now generated once and read by
    both, so a chapter can be left to whichever pipeline actually has its data.
    """
    out = []
    for p in sorted(CHAPTERS.glob("*.json")):
        if p.stem.startswith("_"):
            continue
        cfg = json.loads(p.read_text(encoding="utf-8"))
        if cfg.get("managed"):
            continue
        has_src = (ROOT / cfg.get("source_dir", "") / "src" / "pages").is_dir()
        if has_src or cfg.get("infra", {}).get("shared_container"):
            out.append(p.stem)
    return out


def run_step(name, what, argv, cwd=ROOT, timeout=900):
    """Run one step and describe the outcome the way the status page needs it."""
    started = now()
    t0 = time.time()
    try:
        r = subprocess.run([PY] + argv, cwd=str(cwd), capture_output=True,
                           text=True, timeout=timeout)
        ok = r.returncode == 0
        tail = (r.stdout or r.stderr or "").strip().splitlines()
        detail = tail[-1][:200] if tail else ("ok" if ok else "no output")
        if not ok and r.stderr:
            detail = r.stderr.strip().splitlines()[-1][:200]
    except subprocess.TimeoutExpired:
        ok, detail = False, f"timed out after {timeout}s"
    except Exception as e:  # noqa: BLE001
        ok, detail = False, f"{type(e).__name__}: {e}"
    return {"name": name, "what": what, "last_run": started, "ok": ok,
            "detail": detail, "seconds": round(time.time() - t0, 1)}


def _link_summary(key):
    """Re-run the checker capturing its JSON, so the status page can say what
    broke instead of showing the last line of a JSON document ("}").

    verify_links.py exits with the failure count, which is the right contract for
    gating a deploy and the wrong thing to show a reader.
    """
    try:
        r = subprocess.run(
            [PY, "research/verify_links.py", "--json", "--chapter", key],
            cwd=str(ROOT), capture_output=True, text=True, timeout=600)
        d = json.loads(r.stdout)
    except Exception:  # noqa: BLE001
        return {}
    n, bad = d.get("checked", 0), d.get("failed", 0)
    if bad:
        first = d["failures"][0]
        detail = (f"{bad} of {n} links dead - e.g. {first['url']} "
                  f"({first['code']})")
    else:
        detail = f"all {n} links reachable"
    return {"ok": bad == 0, "detail": detail}



def _in_research(key):
    """Whether research/cities.json carries this chapter's links."""
    try:
        d = json.loads((ROOT / "research" / "cities.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    return any(c.get("key") == key for c in d.get("cities", []))


def weekly(key, since, quiet=False):
    cfg = load(key)
    jobs = []

    # A step a chapter was never configured for is not a failure. San Angelo and
    # Southaven predate both the portal adapters and the verified-links file;
    # reporting those as errors would put a permanent red row on their public
    # automation page for work nobody ever asked the timer to do, which is the
    # precise false alarm that page exists to avoid.
    if (cfg.get("portal") or {}).get("vendor"):
        jobs.append(run_step(
            "Meetings", f"Pull agendas and video from {cfg['city']}'s own portal",
            ["shared/ingest_meetings.py", key, "--since", since, "--quiet"]))
    else:
        jobs.append({"name": "Meetings", "what": "Pull agendas from the city's portal",
                     "last_run": now(), "ok": True, "seconds": 0.0,
                     "detail": "not automated for this chapter - its archive is "
                               "maintained by its own pipeline"})

    if _in_research(key):
        link = run_step(
            "Link check", "Re-fetch every external link this chapter publishes",
            ["research/verify_links.py", "--json", "--chapter", key], timeout=600)
        link.update(_link_summary(key))
        jobs.append(link)
    else:
        jobs.append({"name": "Link check", "what": "Re-fetch every external link",
                     "last_run": now(), "ok": True, "seconds": 0.0,
                     "detail": "this chapter's links are not yet in the verified "
                               "sources file"})

    # Agenda text, capped per run. The archive builds up over successive weeks
    # rather than hammering a city's server in one burst, and the cache means a
    # document is only ever fetched once.
    if (cfg.get("portal") or {}).get("vendor") in ("legistar", "civicplus", "granicus", "civicclerk"):
        jobs.append(run_step(
            "Agenda text", "Extract the text of each agenda so it can be searched",
            ["shared/extract_agendas.py", key, "--limit", "60", "--quiet"],
            timeout=1800))

    # The build must happen even if the ingest failed. The rest of the site -
    # the statute, the city desk, the letter builder - is not downstream of one
    # city's portal being unreachable, and leaving it un-rebuilt would mean a
    # single outage freezes the whole chapter.
    jobs.append(run_step(
        "Build", "Re-render every page from the chapter config",
        ["build.py", key, "--quiet"]))

    cfg = load(key)  # ingest may have flipped features.meetings on
    if cfg["features"].get("site_search"):
        jobs.append(run_step(
            "Search index", "Rebuild the client-side search index",
            ["shared/build_search_index.py", key, "--quiet"]))

    site = (ROOT / cfg["source_dir"] / "site").resolve()
    data = site / "data"
    data.mkdir(parents=True, exist_ok=True)

    # Carry the meetings index into the published site so the count on the
    # automation page and the archive page cannot disagree.
    gen = (ROOT / cfg["source_dir"] / "generated" / "meetings.json").resolve()
    if gen.exists():
        (data / "meetings.json").write_bytes(gen.read_bytes())
        try:
            n = json.loads(gen.read_text(encoding="utf-8")).get("count", 0)
            for j in jobs:
                if j["name"] == "Meetings" and j["ok"]:
                    j["detail"] = f"{n} meetings indexed"
        except (ValueError, OSError):
            pass

    (data / "automation.json").write_text(json.dumps({
        "generated_at": now(),
        "chapter": key,
        "city": cfg["city"],
        "jobs": jobs,
    }, indent=2), encoding="utf-8")

    failed = [j["name"] for j in jobs if not j["ok"]]
    if not quiet:
        status = "OK" if not failed else "FAILED: " + ", ".join(failed)
        print(f"  {key:12s} {len(jobs)} jobs  {status}")
        for j in jobs:
            mark = "ok " if j["ok"] else "ERR"
            print(f"      {mark} {j['name']:14s} {j['seconds']:6.1f}s  {j['detail']}")
    return len(failed)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("keys", nargs="*")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--since", default="2025-01-01")
    ap.add_argument("--deploy", action="store_true",
                    help="push each chapter after refreshing it")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    keys = city_keys() if args.all else args.keys
    if not keys:
        raise SystemExit("name chapters, or pass --all")

    print(f"== weekly refresh {now()}")
    failed = 0
    for k in keys:
        try:
            failed += weekly(k, args.since, args.quiet)
        except Exception as e:  # noqa: BLE001 - never let one chapter stop the run
            failed += 1
            print(f"  {k:12s} RUN FAILED: {type(e).__name__}: {e}")

    # The hubs summarise the chapters, so they are regenerated after the chapters
    # are refreshed and before anything is pushed. Both read the same generated
    # meetings.json the chapter pages do, which is what keeps the counts on
    # foundation.moveweight.com from drifting away from the archives themselves.
    # Crawl the sites' own links. This is a different failure from the outbound
    # link check: it catches a nav or footer entry pointing at a page the build
    # did not produce, which is what put a 404 behind "Fund a public records
    # request" on every Mississippi page until Austin reported it. Nothing was
    # watching for it, so now the timer is.
    print("\n== site links")
    j = run_step("Site links", "Crawl every chapter for broken internal links",
                 ["research/verify_site_links.py"], timeout=1200)
    print(f"      {'ok ' if j['ok'] else 'ERR'} Site links     {j['detail']}")
    failed += (not j["ok"])

    print("\n== hubs")
    # Maps first: both hubs embed the SVG, so regenerating them in the other
    # order would publish last week's pin set for a week.
    for name, argv in (("Maps", ["shared/make_maps.py"]),
                       # Emitted every week and deployed to Miami's standardiser,
                       # which is the only chapter that cannot render the bar
                       # itself. Without this its copy freezes and drifts - which
                       # is how three different "universal" bars ended up live.
                       ("Chapter bars", ["shared/make_chapterbars.py"]),
                       ("State hubs", ["shared/make_state_hubs.py"]),
                       ("Foundation", ["shared/make_foundation.py", "--deploy"])):
        j = run_step(name, "Regenerate the chapter directory", argv, timeout=300)
        print(f"      {'ok ' if j['ok'] else 'ERR'} {name:14s} {j['detail']}")
        failed += (not j["ok"])

    # make_state_hubs writes a `state.html` FRAGMENT into whichever chapter hosts
    # the hub, and a fragment is only HTML after build.py renders it. The per
    # chapter builds above already ran, so without this pass the hub page pushed
    # to each state apex is the one built from last week's fragment - which is
    # how the national map gained eleven pins and the state maps kept three.
    for k in keys:
        j = run_step("Rebuild", "Render the regenerated state hub fragment",
                     ["build.py", k, "--quiet"], timeout=120)
        if not j["ok"]:
            print(f"      ERR Rebuild {k}: {j['detail']}")
            failed += 1

    if args.deploy:
        print("\n== deploy")
        # Pass --all rather than the key list when refreshing everything, so the
        # deploy uses provision.py's `deployable_chapters()` - which includes San
        # Angelo and Southaven. They are template-built but not shared-container
        # tenants, and naming keys here is what left them out of every deploy
        # until their chapter bar was three revisions stale.
        target = ["--all"] if len(keys) == len(city_keys()) else keys
        r = subprocess.run([PY, "shared/deploy/provision.py"] + target
                           + ["--site", "--bars", "--hubs"], cwd=str(ROOT))
        failed += (r.returncode != 0)

    print(f"\n  {len(keys)} chapters, {failed} failed steps")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
