#!/usr/bin/env python3
"""
Scaffold the next Expose chapter.

    python new_chapter.py --key tulsa --city Tulsa --county "Tulsa County" \
        --state Oklahoma --abbr OK --domain exposetulsa.com --vmid 177

Writes chapters/<key>.json, creates the chapter source directory with a starter
index fragment, and prints the launch checklist. It does not touch any server —
provisioning is deploy/provision.sh, run deliberately and separately.

The generated config starts with the core features on and every archive feature
off, because a chapter with no meetings archive should not ship an empty meetings
page. Turn each on in FEATURES.md order as the local data source appears.
"""

import argparse
import json
import re
import sys
from pathlib import Path

# Windows consoles default to cp1252 and will crash on the arrows below.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except AttributeError:
    pass

ROOT = Path(__file__).resolve().parent
CHAPTERS = ROOT / "chapters"

# Statute defaults by state. Adding a state here is the single biggest thing that
# makes a new chapter correct on day one — the response window and the appeal
# forum drive the request letter, the UI copy and the follow-up schedule.
#
# `appeal.sentence` is written out per state rather than assembled from parts.
# An earlier version glued a free/not-free clause onto a `powers` fragment and
# produced "That route is not free, and it the body must seek an AG decision to
# withhold" on every Texas chapter. Prose about a reader's legal remedy is the
# last thing that should be generated by string concatenation.
STATUTES = {
    "MS": {
        "name": "Mississippi Public Records Act",
        "citation": "Miss. Code Ann. § 25-61-1 et seq.",
        "response_section": "§ 25-61-5", "response_window": "seven (7) working days",
        "fee_section": "§ 25-61-7", "fee_threshold": "$25.00", "residency_required": False,
        "appeal": {
            "body": "Mississippi Ethics Commission", "citation": "§ 25-61-13",
            "free": True,
            "powers": "can order the record released and impose a civil penalty on the "
                      "official who wrongfully withheld it",
            "sentence": "A denial appeals <strong>free</strong> to the Mississippi Ethics "
                        "Commission under &sect; 25-61-13. The Commission can order the "
                        "record released and impose a civil penalty on the official who "
                        "wrongfully withheld it. This is the strongest citizen remedy of "
                        "the three states this Foundation works in, and almost nobody "
                        "uses it.",
        },
    },
    "TX": {
        "name": "Texas Public Information Act",
        "citation": "Tex. Gov't Code ch. 552",
        "response_section": "§ 552.301", "response_window": "ten (10) business days",
        "fee_section": "§ 552.2615", "fee_threshold": "$40.00", "residency_required": False,
        "appeal": {
            "body": "Texas Attorney General", "citation": "§ 552.301",
            "free": False,
            "powers": "rules on whether the body may withhold, on the body's own request",
            # The AG ruling process is started by the governmental body, not by
            # the requester. Describing it as "your appeal" would tell a Texan
            # they have a forum they do not have.
            "sentence": "Texas has no free citizen appeal board. If the City wants to "
                        "withhold, <em>it</em> must ask the Attorney General for a ruling "
                        "within ten business days (&sect; 552.301) and send you a copy of "
                        "what it asked &mdash; that request and the ruling are both public, "
                        "and they are the best record of what a city tried to hide. If the "
                        "City simply never answers, a complaint goes to the county or "
                        "district attorney under &sect; 552.3215, or you can sue for "
                        "mandamus under &sect; 552.321.",
        },
    },
    "OK": {
        "name": "Oklahoma Open Records Act",
        "citation": "51 O.S. § 24A.1 et seq.",
        "response_section": "§ 24A.5", "response_window": "prompt, reasonable time",
        "fee_section": "§ 24A.5(3)", "fee_threshold": "$25.00", "residency_required": False,
        "appeal": {
            "body": "district court", "citation": "51 O.S. § 24A.17",
            "free": False,
            "powers": "civil action; a prevailing requester can recover attorney fees",
            # Oklahoma's "prompt and reasonable" standard has no fixed number in
            # it, which makes delay the default tactic and a dated written record
            # of that delay the only thing that answers it.
            "sentence": "Oklahoma has no administrative appeal and no fixed deadline &mdash; "
                        "only a &ldquo;prompt, reasonable&rdquo; standard, which makes delay "
                        "the default tactic. Enforcement is a civil action in district court "
                        "under 51 O.S. &sect; 24A.17, and a requester who prevails can "
                        "recover attorney fees, which is what makes the remedy usable at "
                        "all. Because the deadline is a standard rather than a number, a "
                        "dated written record of every follow-up is the case.",
        },
    },
}

ACCENTS = [
    ("#e8590c", "#ff922b", "#c44a09"),
    ("#e03131", "#ff6b6b", "#c62828"),
    ("#dc2626", "#ef4444", "#b91c1c"),
    ("#0ca678", "#20c997", "#087f5b"),
    ("#7048e8", "#9775fa", "#5f3dc4"),
    ("#1971c2", "#4dabf7", "#1864ab"),
]

STARTER_INDEX = """<!--meta
out: index.html
title: {site_name} — {city}, {state}
bare_title: true
description: A public records project of the Move Weight Foundation covering {city}, {state}.
-->

<section class="hero">
  <div class="wrap">
    <span class="eyebrow">{city} &middot; {county} &middot; {state}</span>
    <h1>Replace this with the one fact that made you build this chapter.</h1>
    <p class="lede">
      One paragraph. What is happening in {city}, what document proves it, and what the
      public has not been shown. Every claim on this site links to a primary document
      or a named outlet &mdash; write nothing here you cannot source.
    </p>
    <div class="hero-btns">
      <a class="btn btn-red btn-lg" href="/records/">File a records request &rarr;</a>
      <a class="btn btn-ghost btn-lg" href="/city-desk.html">City Desk</a>
      <a class="btn btn-ghost btn-lg" href="/tips.html">Send an anonymous tip</a>
    </div>
  </div>
</section>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", required=True, help="short key, e.g. tulsa")
    ap.add_argument("--city", required=True)
    ap.add_argument("--county", required=True)
    ap.add_argument("--state", required=True)
    ap.add_argument("--abbr", required=True, help="two-letter state code")
    ap.add_argument("--domain", required=True)
    ap.add_argument("--vmid", type=int, required=True)
    ap.add_argument("--ip", help="default 192.168.0.<vmid>")
    ap.add_argument("--canonical-host", help="default = domain")
    args = ap.parse_args()

    key = args.key.lower()
    if not re.fullmatch(r"[a-z0-9-]+", key):
        sys.exit("key must be lowercase letters, digits and hyphens")

    dest = CHAPTERS / f"{key}.json"
    if dest.exists():
        sys.exit(f"{dest} already exists — edit it rather than regenerating")

    abbr = args.abbr.upper()
    statute = STATUTES.get(abbr)
    if not statute:
        print(f"  ! No statute template for {abbr}. Writing a stub — you MUST fill it in")
        print(f"    before the records page is truthful. Add {abbr} to STATUTES in this script.")
        statute = {"name": f"{args.state} public records law", "citation": "TODO",
                   "response_section": "TODO", "response_window": "TODO",
                   "fee_section": "TODO", "fee_threshold": "TODO",
                   "residency_required": None,
                   "appeal": {"body": "TODO", "citation": "TODO", "free": None, "powers": "TODO"}}

    existing = len([c for c in CHAPTERS.glob("*.json") if not c.stem.startswith("_")])
    accent, accent2, hover = ACCENTS[existing % len(ACCENTS)]
    site_name = "Expose" + "".join(w.capitalize() for w in re.split(r"[\s-]+", args.city))

    cfg = {
        "key": key,
        "site_name": site_name,
        "logo": {"prefix": "Expose", "body": site_name[len("Expose"):]},
        "domain": args.domain,
        "canonical_host": args.canonical_host or args.domain,
        "hosts": [args.domain, f"www.{args.domain}"],
        "chapter_label": f"{args.city}, {abbr}",
        "city": args.city, "county": args.county,
        "state": args.state, "state_abbr": abbr,
        "accent": accent, "accent2": accent2, "accent_hover": hover,
        "infra": {
            "vmid": args.vmid,
            "ip": args.ip or f"192.168.0.{args.vmid}",
            "node": "Slimmm",
            "cores": 4, "memory_mb": 8192, "swap_mb": 4096, "disk_gb": 40,
            "records_port": 5060, "signup_port": 5050,
            "web_root": f"/var/www/expose{key}/html",
            "app_root": f"/opt/expose{key}",
        },
        "statute": statute,
        "donations": {"url": "/about.html#funding", "live": False,
                      "zelle": "team@moveweight.com"},
        "features": {
            "city_desk": True, "records": True, "tips": True, "signup": True,
            "documents": True, "news": True, "officials": True,
            "site_search": False, "meetings": False, "agenda_packets": False,
            "court_search": False, "crime_watch": False, "mayor_watch": False,
            "automation_status": False, "evidence_api": False,
        },
        "allies": [],
    }

    dest.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")

    src = ROOT.parent / f"expose{key}" / "src" / "pages"
    src.mkdir(parents=True, exist_ok=True)
    starter = src / "00-index.html"
    if not starter.exists():
        starter.write_text(STARTER_INDEX.format(
            site_name=site_name, city=args.city, county=args.county,
            state=args.state), encoding="utf-8")

    print(f"""
  Created  {dest.relative_to(ROOT)}
  Created  {starter}

  Launch checklist
  ----------------
   1. Verify the statute block. {abbr} response window: {statute['response_window']}
      Appeal: {statute['appeal']['body']} ({'free' if statute['appeal'].get('free') else 'not free'})
   2. Fill in custodians          -> chapters/{key}.json  (see mississippi.json)
   3. Transcribe the department directory from the city's OWN published source.
      Never invent a government phone number.
   4. Write src/pages/00-index.html around one documented fact.
   5. python build.py {key}
   6. sh shared/deploy/provision.sh {key}      (creates LXC {args.vmid}, installs, deploys)
   7. Add proxied Cloudflare A records for: {', '.join(cfg['hosts'])} -> 173.207.168.55
      The Traefik API token only covers moveweight.com, so use the dashboard.
   8. Test with EXPOSE_SUPPRESS_CUSTODIAN=1 BEFORE any live submission.
   9. Add the chapter to CHAPTER_ORDER in build.py and rebuild the others,
      so every chapter bar lists it.
  10. Write the GoFundMe kit; leave donations.live false until it exists.
""")


if __name__ == "__main__":
    main()
