#!/usr/bin/env python3
"""
Hold ExposeMiamiOK to the Move Weight Foundation chapter standard.

Several of this site's pages are regenerated by scheduled jobs that live
outside the container, so anything injected into the HTML once gets wiped the
next time those jobs run — which is why the chapter bar survived on only 4 of
16 top-level pages. Rather than chase every generator, this runs on a timer and
re-applies the standard to whatever is currently on disk.

Everything here is idempotent: a page that already complies is left untouched,
so running it every 15 minutes costs nothing.

What it enforces
  1. The shared chapter bar (identical markup on all three chapter sites)
  2. <link rel=canonical>, og:title, og:type, og:site_name
  3. <meta name=description> derived from the page's own <title> when absent
  4. Removal of "Loading" / "Site Links" placeholders left by the scraper that
     built the resources/ department pages

Usage:  python3 mw_standardize.py [--dry-run] [--quiet]
"""

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path

HTML = Path("/var/www/exposemiamiok/html")
BASE = "https://miami.exposeoklahoma.com"
SITE = "ExposeMiamiOK"
THEME = "/assets/exposemiami-theme.css"

BAR_FILE = Path("/opt/expose-chapterbar.html")

# The bar is generated once by the template (shared/make_chapterbars.py) and
# deployed here. It used to be a hardcoded copy in this file, which is how Miami
# ended up serving a bar naming three chapters and three retired domains long
# after there were fourteen chapters on new ones - every link a 404.
#
# If the file is missing this is None and the bar step is skipped entirely,
# because silently writing an empty bar across 764 pages is far worse than
# leaving yesterday's.
try:
    BAR = BAR_FILE.read_text(encoding="utf-8").strip()
except OSError:
    BAR = None

# Pages that are internal tooling, not public pages — left alone entirely.
SKIP_NAMES = {"admin.html", "welcome-email.html"}

# Dated archives regenerate constantly and are not indexed individually.
SKIP_DIRS = {"meetings", "agenda-packets", "facebook-posts",
             "finance-transcripts", "documents"}

# The donate banner. Miami carried it on 5 of 13 pages - not on /foia/, not on
# /meetings/, not on the City Desk - so the chapter with the longest archive and
# the most traffic asked for money on the pages a reader was least likely to see.
# Injected here for the same reason the chapter bar is: several of these pages are
# regenerated by jobs outside this container, which wipes anything added by hand.
#
# The Zelle address is split across three spans on purpose. Cloudflare's email
# obfuscation rewrites a bare address into "[email protected]", which is exactly
# what the existing banner on this chapter still shows.
NL = chr(10)

# Cloudflare rewrote the Zelle address into an obfuscated anchor that renders
# as "[email protected]". Swap it for the split-span form, which Scrape Shield
# leaves alone because there is no bare address to find.

CF_EMAIL_RE = re.compile(
    r'<a href="/cdn-cgi/l/email-protection"[^>]*>\[email[^<]*</a>')
ZELLE_SPANS_PLAIN = (
    '<span class="sm-u">team</span><span class="sm-at">&#64;</span>'
    '<span class="sm-d">moveweight.com</span>')

ZELLE_SPANS = ('<span class="sm-u">team</span><span class="sm-at">&#64;</span>'
               '<span class="sm-d">moveweight.com</span>')

BARE_ZELLE = '<strong>team@moveweight.com</strong>'
BARE_ZELLE_FIXED = '<strong>' + ZELLE_SPANS_PLAIN + '</strong>'

DONATE_BANNER = (
    '<div class="donate-banner">This site is funded by citizens, not by the '
    'city. <a href="https://www.gofundme.com/f/fund-public-records-access-in-miami-ok">Fund a public records request '
    '&rarr;</a><span class="sep hide-sm">|</span><span class="hide-sm">Zelle: '
    '<strong><span class="sm-u">team</span><span class="sm-at">&#64;</span>'
    '<span class="sm-d">moveweight.com</span></strong></span>'
    '<span class="sep hide-sm">|</span><span class="hide-sm">'
    '501(c)(3) tax-deductible</span></div>'
)

import sys as _sys
_sys.path.insert(0, '/opt')
try:
    from nav_constants import HEADER_HTML as SITE_NAV
except Exception:
    SITE_NAV = ''

NAV_START = '<div class="mw-unified-shell">'

BODY_RE = re.compile(r"(<body\b[^>]*>)", re.I)
HEAD_RE = re.compile(r"</head>", re.I)
TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)

FALLBACK_DESC = ("ExposeMiamiOK is the Move Weight Foundation's Miami, Oklahoma "
                 "chapter — city council meetings, open records requests, and "
                 "public documents, published in full.")




def _theme_href(path):
    """A stylesheet path with a hash of ITS OWN contents appended."""
    f = HTML / path.lstrip("/")
    try:
        h = hashlib.md5(f.read_bytes()).hexdigest()[:8]
    except OSError:
        return path
    return f"{path}?v={h}"


# Miami links two different stylesheets across its pages - 751 use
# exposemiami-theme.css and 10, including the homepage, use theme.css. Both are
# hashed, or the front page keeps serving a cached stylesheet that predates the
# chapter bar it is now rendering.
THEME_LINK_RE = re.compile(
    r'(<link[^>]+href=")(/assets/(?:exposemiami-)?theme\.css)(\?v=[^"]*)?(")')

def _nav_span(text):
    """(start, end) of the existing site nav shell, by balanced <div> count."""
    i = text.find(NAV_START)
    if i < 0:
        return None
    depth = 0
    for m in re.finditer(r'<div|</div>', text[i:]):
        if m.group(0) == '</div>':
            depth -= 1
            if depth == 0:
                return (i, i + m.end())
        else:
            depth += 1
    return None


def all_html_pages(root):
    """Every .html under the web root, following symlinked directories.

    rglob() and find(1) do not descend into a symlinked directory, and
    resources/miamiok is one - it points at /var/www/exposemiamiok/mirror/
    www.miamiok.gov, a mirror of the City's own site kept so those pages stay
    readable when the City moves or retires them. 39 pages sat behind that link
    and this script had never once seen them: no chapter bar, no donate banner,
    no navigation, for as long as the mirror has existed.

    followlinks=True needs a loop guard, so directories are visited once by
    resolved real path.
    """
    seen_dirs = set()
    out = []
    for dp, dn, fn in os.walk(str(root), followlinks=True):
        real = os.path.realpath(dp)
        if real in seen_dirs:
            dn[:] = []
            continue
        seen_dirs.add(real)
        for f in fn:
            if f.lower().endswith((".html", ".htm")):
                out.append(Path(dp) / f)
    return sorted(out)


ASSETS = Path("/var/www/exposemiamiok/html/assets")


def _asset_ver(name):
    """Cache-busting token for /assets/<name>, derived from the file itself.

    These were hand-typed constants. That meant editing the stylesheet or the
    script did not change the URL a page asked for, so a reader who had been
    here before kept serving themselves the old copy out of cache. It is how
    the corrected navigation could be live on disk and still reach nobody.
    """
    try:
        return hashlib.sha256((ASSETS / name).read_bytes()).hexdigest()[:8]
    except OSError:
        return "0"


SITE_JS_VER = _asset_ver("exposemiami-ui.js")
SITE_CSS_VER = _asset_ver("exposemiami-theme.css")

# Deliberately no quote character in the class: a version token is word chars,
# dot and dash, and matching on quotes is what makes this pattern fragile to
# write through a shell heredoc.
ASSET_REF_RE = re.compile(
    r"(/assets/exposemiami-(?:theme\.css|ui\.js))(\?v=[\w.-]*)?"
)


def refresh_asset_refs(text):
    """Point every existing asset reference at the current content hash.

    ensure_site_assets() only ever INJECTED a tag when one was missing, so the
    pages already carrying "?v=20260601-unified-menu-agenda6" kept asking for
    that URL forever, and never saw a corrected script.
    """
    def sub(m):
        path = m.group(1)
        ver = SITE_CSS_VER if path.endswith(".css") else SITE_JS_VER
        return path + "?v=" + ver
    return ASSET_REF_RE.sub(sub, text)


def ensure_site_assets(text):
    """A page carrying the site nav must load the CSS AND the JS that drive it.

    Miami keeps its own stylesheet and its own script separate from the chapter
    template's. Injecting the nav markup alone produced two different failures:
    without /assets/exposemiami-theme.css the off-canvas drawer and the desktop
    nav rendered as unstyled rows of links stacked under the header, and without
    /assets/exposemiami-ui.js the hamburger did nothing - which on this site is
    total, because the desktop nav computes to display:none at the widths tested
    and the drawer is then the only navigation there is.
    """
    changed = False
    if "mw-unified-shell" not in text:
        return text, False

    if "exposemiami-theme" not in text and HEAD_RE.search(text):
        link = ('<link rel="stylesheet" href="/assets/exposemiami-theme.css?v='
                + SITE_CSS_VER + '">')
        text = HEAD_RE.sub(lambda m: "  " + link + NL + m.group(0), text, count=1)
        changed = True

    if "exposemiami-ui.js" not in text:
        tag = ('<script src="/assets/exposemiami-ui.js?v=' + SITE_JS_VER
               + '" defer></script>')
        if re.search(r"</body>", text, re.I):
            text = re.sub(r"</body>", tag + NL + "</body>", text, count=1,
                          flags=re.I)
            changed = True
        elif HEAD_RE.search(text):
            text = HEAD_RE.sub(lambda m: "  " + tag + NL + m.group(0), text,
                               count=1)
            changed = True

    refreshed = refresh_asset_refs(text)
    if refreshed != text:
        text, changed = refreshed, True
    return text, changed


def strip_all_navs(text):
    """Remove every mw-unified-shell block. Returns (text, count).

    Replacing "the" nav in place is what broke this the first time: pages carried
    three vintages of the markup, the balanced-div scan came out short on some of
    them, and each run left a tail behind while adding a fresh copy. Pages reached
    twelve stacked navs. Removing all of them and inserting exactly one is the
    only version of this that is safe to run repeatedly.
    """
    n = 0
    while True:
        i = text.find(NAV_START)
        if i < 0:
            return text, n
        depth = 0
        end = None
        for mm in re.finditer(r"<div\b|</div>", text[i:]):
            depth += 1 if mm.group(0) != "</div>" else -1
            if depth == 0:
                end = i + mm.end()
                break
        if end is None:
            return text, n
        text = text[:i] + text[end:]
        n += 1
        if n > 40:          # a page this broken needs a human, not another pass
            return text, n


def apply_site_nav(text):
    """Exactly one current site nav per page."""
    if not SITE_NAV:
        return text, None
    stripped, n = strip_all_navs(text)
    if n == 1 and SITE_NAV in text:
        return text, None            # already correct, leave the bytes alone
    text = stripped
    hit = re.search(r'<div class="donate-banner">.*?</div>', text, re.S)
    if hit:
        text = text[:hit.end()] + NL + SITE_NAV + text[hit.end():]
    elif BODY_RE.search(text):
        text = BODY_RE.sub(lambda mo: mo.group(1) + NL + SITE_NAV, text, count=1)
    else:
        return text, None
    return text, ("sitenav-updated" if n else "sitenav")


def _bar_span(text):
    """(start, end) of the existing chapter bar div, by balanced <div> count."""
    i = text.find('<div class="chapterbar"')
    if i < 0:
        return None
    depth, j = 0, i
    tag = re.compile(r"<(/?)div\b", re.I)
    while j < len(text):
        m = tag.search(text, j)
        if not m:
            return None
        depth += -1 if m.group(1) else 1
        j = m.end()
        if depth == 0:
            end = text.find(">", j)
            return (i, end + 1 if end > 0 else j)
    return None

def esc(s):
    return (s.replace("&", "&amp;").replace('"', "&quot;")
             .replace("<", "&lt;").replace(">", "&gt;"))


def canonical_for(p: Path) -> str:
    rel = p.relative_to(HTML).as_posix()
    if rel == "index.html":
        return BASE + "/"
    if rel.endswith("/index.html"):
        return f"{BASE}/{rel[:-len('index.html')]}"
    return f"{BASE}/{rel}"


def should_skip(p: Path) -> bool:
    rel = p.relative_to(HTML)
    if p.name in SKIP_NAMES:
        return True
    return bool(rel.parts[:-1]) and rel.parts[0] in SKIP_DIRS



def bar_only(text, insert=True):
    """Swap the chapter bar, repoint dead links, carry the donate banner.

    These are the dated archive pages. They are still public pages a reader
    reaches from the nav - /meetings/ most of all - so leaving them without
    a donate route made the ask absent from the part of the site with the
    deepest content.
    """
    text = fix_legacy_links(text)
    if not BAR:
        return text

    if "data-mw-chapterbar" not in text:
        if not insert:
            return text
        # These pages never had a bar to replace, and this function only
        # ever swapped an existing one - so 112 of Miami's 766 pages had
        # no chapter nav at all. Every finance transcript, a quarter of the
        # agenda packets, and the meetings index, which is the single
        # deepest page on the chapter. Insert rather than skip.
        if BODY_RE.search(text):
            add = BAR + (NL + DONATE_BANNER if "donate-banner" not in text else "")
            text = BODY_RE.sub(lambda m: m.group(1) + NL + add, text, count=1)
        return text
    cut = _bar_span(text)
    if cut and text[cut[0]:cut[1]].strip() != BAR:
        text = text[:cut[0]] + BAR + text[cut[1]:]
    if "donate-banner" not in text:
        cut = _bar_span(text)
        if cut:
            text = text[:cut[1]] + NL + DONATE_BANNER + text[cut[1]:]
    text, _ = apply_site_nav(text)
    text, _ = ensure_site_assets(text)
    return text


# Miami's own pages, versus the paths its footer was written against. The left
# side does not exist on this chapter and never did; the right side is what it
# actually publishes. Verified live before being written down.
LEGACY_PATH_FIXES = {
    '/records/': '/foia/',
    '/news.html': '/local-news.html',
    '/about.html': 'https://foundation.moveweight.com/#about',
    '/documents/': '/foia/',
}


def fix_legacy_links(text):
    """Repoint hrefs at pages this chapter really has.

    Matched on the PATH with any #anchor preserved. The first version compared
    whole href strings, so it repaired href="/records/" and silently missed
    href="/records/#appeal" - which is the form the Foundation footer actually
    uses, and the reason three dead links survived the fix that was supposed to
    remove them.
    """
    def repl(m):
        path, frag = m.group(1), m.group(2) or ''
        good = LEGACY_PATH_FIXES.get(path)
        if not good:
            return m.group(0)
        # An anchor is meaningless once the target page changes.
        return 'href="' + good + ('' if good.startswith('http') else frag) + '"'
    return re.sub(r'href="([^"#]+)(#[^"]*)?"', repl, text)

def standardize(text: str, p: Path):
    """Return (new_text, [what changed])."""
    changes = []

    # ── stylesheet, so the bar is never unstyled ───────────────────────
    # Pages built from the shared template already link /assets/theme.css,
    # which carries the topbar, nav and chapter-bar rules. Injecting Miami OK's
    # older sheet *after* it let the old rules win and the main menu rendered
    # unstyled. Archive pages, which the template does not build, still need it.
    if "/assets/theme.css" in text:
        pass
    elif THEME not in text and HEAD_RE.search(text):
        text = HEAD_RE.sub(
            f'<link rel="stylesheet" href="{THEME}">\n</head>', text, count=1)
        changes.append("theme")

    # Keep the stylesheet href pointing at the current content hash. Without
    # this a CSS change sits behind a 7-day cache and never reaches anyone.
    if THEME_LINK_RE.search(text):
        new = THEME_LINK_RE.sub(
            lambda m: m.group(1) + _theme_href(m.group(2)) + m.group(4), text)
        if new != text:
            text = new
            changes.append("theme-version")

    fixed = fix_legacy_links(text)
    if fixed != text:
        text = fixed
        changes.append("deadlinks")

    # ── chapter bar ────────────────────────────────────────────────────
    if BAR:
        if "data-mw-chapterbar" in text:
            # Replace whatever bar is there. The old version only ever inserted
            # when none was present, so a bar that was wrong stayed wrong
            # forever - which is precisely what happened.
            cut = _bar_span(text)
            if cut and text[cut[0]:cut[1]].strip() != BAR:
                text = text[:cut[0]] + BAR + text[cut[1]:]
                changes.append("chapterbar-updated")
        elif BODY_RE.search(text):
            text = BODY_RE.sub(lambda m: m.group(1) + "\n" + BAR, text, count=1)
            changes.append("chapterbar")

    # -- donate banner -------------------------------------------------
    # Straight after the bar, so the two always read as one header block.
    # no-bar donate: some generated index pages carry no chapter bar, so the
    # bar-anchored injection above never fires on them.
    if ("donate-banner" not in text and "data-mw-chapterbar" not in text
            and BODY_RE.search(text)):
        text = BODY_RE.sub(lambda m: m.group(1) + NL + DONATE_BANNER,
                           text, count=1)
        changes.append("donate-banner-nobar")

    if "donate-banner" not in text and "data-mw-chapterbar" in text:
        cut = _bar_span(text)
        if cut:
            text = text[:cut[1]] + NL + DONATE_BANNER + text[cut[1]:]
            changes.append("donate-banner")

    text, _nav = apply_site_nav(text)
    if _nav:
        changes.append(_nav)
    text, _css = ensure_site_assets(text)
    if _css:
        changes.append("site-assets")

    if BARE_ZELLE in text:
        text = text.replace(BARE_ZELLE, BARE_ZELLE_FIXED)
        changes.append("zelle-unmangled")

    if CF_EMAIL_RE.search(text):
        text = CF_EMAIL_RE.sub(ZELLE_SPANS, text)
        changes.append("zelle-unmangled")

    # ── head metadata ──────────────────────────────────────────────────
    if HEAD_RE.search(text):
        m = TITLE_RE.search(text)
        title = re.sub(r"\s+", " ", m.group(1)).strip() if m else SITE
        add = []

        # The domain moved; a canonical still naming exposemiamiok.com would
        # fight the 301 and tell search engines two different things.
        text = re.sub(r'<link rel="canonical" href="https://exposemiamiok\.com([^"]*)">',
                      lambda mm: f'<link rel="canonical" href="{BASE}{mm.group(1)}">', text)
        text = text.replace('property="og:url" content="https://exposemiamiok.com',
                            f'property="og:url" content="{BASE}')
        if 'rel="canonical"' not in text and "rel='canonical'" not in text:
            add.append(f'<link rel="canonical" href="{canonical_for(p)}">')
        if "og:title" not in text:
            add.append(f'<meta property="og:title" content="{esc(title)}">')
            add.append('<meta property="og:type" content="website">')
            add.append(f'<meta property="og:site_name" content="{SITE}">')
            add.append(f'<meta property="og:url" content="{canonical_for(p)}">')
        if not re.search(r'name=["\']description["\']', text, re.I):
            # Prefer the page's own title as the seed; it is more specific than
            # a generic site blurb and these pages have meaningful titles.
            d = title if m and len(title) > 25 else FALLBACK_DESC
            add.append(f'<meta name="description" content="{esc(d)}">')

        if add:
            text = HEAD_RE.sub("\n".join(add) + "\n</head>", text, count=1)
            changes.append(f"head+{len(add)}")

    return text, changes


# Miami OK's nav is emitted by generators outside this container, so a link
# added by hand vanishes on the next run. Inject it here instead, right after
# the Home link, wherever a nav carries one.
NAV_LINK = '<a href="/city-desk.html">City Desk</a>'
HOME_LINK_RE = re.compile(r'(<a\s+href="/"\s*>\s*Home\s*</a>)', re.I)


def add_nav_link(text):
    if "/city-desk.html" in text:
        return text, False
    new, n = HOME_LINK_RE.subn(
        lambda m: m.group(1) + chr(10) + "    " + NAV_LINK, text)
    return (new, True) if n else (text, False)


ARTIFACT_RES = [
    # "Loading" / "Site Links" placeholders the scraper left behind, along
    # with the empty container they sit in.
    re.compile(r"<h[1-6][^>]*>\s*Site Links\s*</h[1-6]>\s*", re.I),
    re.compile(r"<h[1-6][^>]*>\s*Loading\s*</h[1-6]>\s*", re.I),
    re.compile(r"<(p|div|span)[^>]*>\s*Loading\s*</\1>\s*", re.I),
]


def clean_artifacts(text: str):
    n = 0
    for rx in ARTIFACT_RES:
        text, k = rx.subn("", text)
        n += k
    return text, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not HTML.is_dir():
        sys.exit(f"missing {HTML}")

    touched = 0
    tally = {}
    artifacts = 0

    for p in all_html_pages(HTML):
        # Archive pages are exempt from metadata rewriting but NOT from the
        # chapter bar: a stale bar there is 618 pages of dead navigation.
        if should_skip(p):
            try:
                t0 = p.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            t1 = bar_only(t0, insert=p.name not in SKIP_NAMES)
            if t1 != t0:
                if not args.dry_run:
                    p.write_text(t1, encoding="utf-8")
                touched += 1
                tally["chapterbar-archive"] = tally.get("chapterbar-archive", 0) + 1
            continue
        try:
            original = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        text, changes = standardize(original, p)

        text, added = add_nav_link(text)
        if added:
            changes.append("navlink")

        if p.parent.name == "resources":
            text, n = clean_artifacts(text)
            if n:
                artifacts += n
                changes.append(f"artifacts-{n}")

        if text != original:
            touched += 1
            for c in changes:
                key = c.split("-")[0].split("+")[0]
                tally[key] = tally.get(key, 0) + 1
            if not args.dry_run:
                p.write_text(text, encoding="utf-8")

    if not args.quiet or args.dry_run:
        verb = "would update" if args.dry_run else "updated"
        print(f"mw-standardize: {verb} {touched} pages "
              f"({', '.join(f'{k}:{v}' for k, v in sorted(tally.items())) or 'nothing'}"
              f"{f', {artifacts} artifacts removed' if artifacts else ''})")


if __name__ == "__main__":
    main()
